### ISSUE TITLE
Grafana ENVS

### ISSUE THREAD

**Issue by apertureless** [infinityworks/Guide_Rancher_Monitoring#18]
Hey,

is it possible to change the grafana configs? I would love to add the extranal image storage

http://docs.grafana.org/installation/configuration/#external-image-storage

Would be great if there were like ENV Variables to set.

**Comment by Rucknar** [comment]
It's very possible, though it's something that you want to consider when tuning the monitoring for your environment. Are you using the Prometheus catalog entry?

It's intended to get people going, it's by no-means though a production grade system ready for all setups. I'd recommend taking the stack and using it as a starting point.
