### ISSUE TITLE
Kubernetes Support

### ISSUE THREAD

**Issue by zimmertr** [infinityworks/Guide_Rancher_Monitoring#21]
Hello, is it possible to enable support for monitoring a separate Kubernetes environment? How can I add my hosts and have containers running on k8s be monitored similar to Cattle?

**Comment by Rucknar** [comment]
Hey @zimmertr,

When you say add support.. to the guide or to the catalog entry?
I've not got a reference kubernetes environment to play with, i'm open to others contributing though!

**Comment by Rucknar** [comment]
@zimmertr There is a seperate catalog entry for Kubernetes. I think we need to wait for 2.0 to settle first though and i'll re-write the guide.
