### ISSUE TITLE
Aggregate Grafana Hosts into one machine

### ISSUE THREAD

**Issue by obenziane2** [infinityworks/Guide_Rancher_Monitoring#22]
Is there anyway to aggregate Grafana Hosts in to one web panel rather than just hitting every machine host and deploy the container ? Let's we have 500 hosts, do we need to install grafana/prometheues on every machine and access them individually ?

Thanks

**Comment by Rucknar** [comment]
@obenziane2 You should just need one grafana & prometheus for many hosts. As long as they are inside the same rancher environment.
