### ISSUE TITLE
Question: How to scrape metrics form the services inside containers?

### ISSUE THREAD

**Issue by pcornelissen** [infinityworks/Guide_Rancher_Monitoring#24]
I like your catalog entry and adopted it a little bit myself (I use a dedicated volume for the prometheus data so it doesn't get lost during an upgrade and I got rid of the exposed ports).

My services offer prometheus compatible data, but right now I'm lost where I should configure prometheus to fetch these. I'm quite new to prometheus and I want to utilize the auto discovery which is in parts already there, because prometheus picks up all containers.
So I assume there should be a way to scrape for example something via http from http://$containerIPOrHostname:11111/internal/prometheus 
All tutorials I have found add all services/containers hardcoded to the config which is not feasible, because you will forget it sometimes when you add new containers.

Do you have an idea how to achieve this?

**Comment by Rucknar** [comment]
Hey @pcornelissen. The catalog entry is more of a starting point than anything else.
I'd recommend taking a copy of the `prometheus.yml` file that supplied through the prom-conf sidekick. Modify that configuration to include your custom fields and you should be good to go. You can then either swap out the prom-conf container for one of your own, or you can 'bake-in' your own prometheus container with the config inside.

The config file its-self will be hardcoded to an extent, it will however use service discovery to find targets as they come/go. If that's not dynamic enough, prometheus offers a static_config option where you can have a configuration management tool update the file, it's re-read every time the timestamp on that file changes.

I'd check out the docs a little further, the service discovery stuff is pretty well documented, though the documentation sometimes can be a little terse.
