### ISSUE TITLE
Prometheus not monitoring Rancher Server

### ISSUE THREAD

**Issue by pkaramol** [infinityworks/Guide_Rancher_Monitoring#26]
I have restarted my Rancher Server (using external MySQL) with the following command:

`docker run -d --restart=unless-stopped -e CATTLE_PROMETHEUS_EXPORTER=true -p 9108:9108 -p 8080:8080 rancher/server:stable --db-host <rds_endpoint> --db-port 3306 --db-user cattle --db-pass <password> --db-name cattle
`
as suggested [here](https://github.com/infinityworks/Guide_Rancher_Monitoring#enabling-prometheus-metrics-for-the-rancher-server).

In the grafana view (I have installed the relevant prometheus stack), when selecting the Rancher Server tab, there are no data points and all is N/A.

Any suggestions on how to troubleshoot this?

Grafana shows metrics for containers as also my Rancher host..

The setup is on AWS with RDS for the external MySQL.

Here is the list of containers running on my Rancher Host node (RancherOS)

```
infinityworks/prometheus-rancher-exporter:v0.22.52
grafana/grafana:4.2.0
infinityworks/graf-db:11
prom/prometheus:v1.6.0
infinityworks/prom-conf:19
rancher/lb-service-haproxy:v0.7.15
rancher/net:v0.13.7
rancher/net:v0.13.7
prom/node-exporter:latest
rancher/healthcheck:v0.3.3
google/cadvisor:latest
rancher/dns:v0.15.3
rancher/network-manager:v0.7.19
rancher/metadata:v0.9.5
rancher/net:v0.13.7
rancher/net:holder
rancher/agent:v1.2.9
```

**Comment by Rucknar** [comment]
What version of Rancher have you got running? The easiest way is to open up Prometheus, go to the 'targets' page and see if the rancher host is a) listed b) being scraped successfully.

**Comment by pkaramol** [comment]
I am using Rancher `1.6.14`

In the screenshot below, why is there a `http://rancher-server:9108/metrics` endpoint?

I don't remember configuring such an option.

Any suggestions how to change this?

![image](https://user-images.githubusercontent.com/2778429/35848622-728656bc-0b27-11e8-8ffe-9a7d10a87141.png)

Many thx.

**Comment by Rucknar** [comment]
`rancher-server` should either be resolvable to your rancher server box, or an IP address. It's configured when you deploy the catalog entry. To update this, click the 'up to date' box on the stack, choose the latest version and amend the rancher server address.

**Comment by pkaramol** [comment]
Many thanks I will try this and post the results.
It is not editable for the running stack I assume (?) so being unable to edit the existing one I have to deploy a new one?

**Comment by pkaramol** [comment]
Many thanks for the support, that did the job.
I see that the Rancher Server metrics are not in the likes of the Rancher hosts in terms of Mem Free, Mem Avail, CPU usage etc. They are more JVM specific?

Is there a way to treat the Rancher server also as a host (in terms of monitoring the same metrics)?

**Comment by pkaramol** [comment]
Closing this either way since it was not actually an issue.

**Comment by Rucknar** [comment]
The config for prometheus is loaded via the config sidekick. You could clone this http://github.com/infinityworks/prom-conf/ repository and update the prometheus to use your own configuration sidekick. This would stop you from receiving updates to the catalog entry, they would potentially over-ride this config.

**Comment by pkaramol** [comment]
> I'd use node-exporter and run it as a container on the same host as Rancher.

If I just do that, will the metrics start to get collected? (in terms of whether there is any other bootstrapping process needed)

**Comment by Rucknar** [comment]
Running the node exporter would give you the metrics, you'd then need to add a job to Prometheus to scrape those metrics. The config for prometheus is loaded via the config sidekick. You could clone this http://github.com/infinityworks/prom-conf/ repository and update the prometheus to use your own configuration sidekick. This would stop you from receiving updates to the catalog entry, they would potentially over-ride this config.

**Comment by pkaramol** [comment]
👍 thx for the valuable feedback!
