### ISSUE TITLE
Update prometheus version

### ISSUE THREAD

**Issue by sliard** [infinityworks/Guide_Rancher_Monitoring#28]
Did you plan to upgrade prometheus version ?
For the moment your 3.0.0 version uses prometheus 1.6.0 but the last stable version is 2.1.0

Did you continue to update this rancher catalogue ?
And can we help with a pull request ?

Thx

**Comment by Rucknar** [comment]
It's true it's in need of an update. More than welcome any pull requests. I'm expecting to do a 'refresh' when rancher 2.0 launches to incorporate some of the changes and make it a little more up-to-date.

**Comment by sliard** [comment]
Good news if it's still alive :)

I also need update grafana because only version 5 has the mysql datasource.

We have to fork this repo ?
https://github.com/Rucknar/community-catalog/tree/master/templates/Prometheus

No github repo with only your catalogue ?

**Comment by Rucknar** [comment]
That's just my personal fork of Ranchers Catalog. The code is in https://github.com/rancher/community-catalog

Fork off that to make any changes.

**Comment by sliard** [comment]
2 PR :
https://github.com/infinityworks/prom-conf/pull/6
To upgrade configuration
https://github.com/rancher/community-catalog/pull/748
For a new catalogue version.

Be Careful, the second PR can't work before you accept first one..

**Comment by Rucknar** [comment]
Merged prom-conf, built `:20` as a version off it and pushed it up.

**Comment by sliard** [comment]
Merge ok : version 4.0.0 with 
prometheus:v2.1.0
grafana:5.0.0
